### ISSUE TITLE
node-ebuilder-0.4.0 bump requiest

### ISSUE THREAD

**Issue by blshkv** [geaaru/geaaru_overlay#3]
https://github.com/geaaru/node-ebuilder/releases/tag/0.4.0
https://github.com/geaaru/geaaru_overlay/blob/master/dev-node/node-ebuilder/node-ebuilder-0.3.0.ebuild

;-)

**Comment by geaaru** [comment]
Done 209b84281fd5fdd262be13c3029893ac1fe1025b
Thanks
